language: node_js
node_js: 10
  
before_script:
  - npm install firebase-tools -g
  - npm install

script:
  - firebase --non-interactive deploy --only hosting --project "$PROJECT_ID" --token "$TOKEN"
  #- node index.js $BASE_URL $BASE_URL_BACKUP

#- firebase login:ci
# language: node
# deploy: firebase
#  token: $TOKEN
